#!/bin/bash

./configure --prefix=${PREFIX}
make
make check
make install

export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION_VERSION=2
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PREFIX}/lib

cd python
$PYTHON setup.py install --cpp_implementation --old-and-unmanageable

ACTIVATE=$PREFIX/etc/conda/activate.d
DEACTIVATE=$PREFIX/etc/conda/deactivate.d

mkdir -p $ACTIVATE
mkdir -p $DEACTIVATE

cat >$ACTIVATE/protobuf.sh <<EOL
export PROTOBUF_IMPL_BACKUP=$PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
export PROTOBUF_IMPL_VERSION_BACKUP=$PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION_VERSION
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION_VERSION=2
EOL

cat >$DEACTIVATE/protobuf.sh <<EOL
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=$PROTOBUF_IMPL_BACKUP
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION_VERSION=$PROTOBUF_IMPL_VERSION_BACKUP
EOL
