"""This list comes from running the following with SciPy 0.9.0 installed:

import pkgutil
import scipy

print("import scipy")

for importer, modname, ispkg in pkgutil.walk_packages(path=scipy.__path__,
                                                      prefix=scipy.__name__+'.',
                                                      onerror=lambda x: None):
    print("import {}".format(modname))
"""
import scipy
import scipy.__config__
import scipy.cluster
import scipy.cluster._hierarchy_wrap
import scipy.cluster._vq
import scipy.cluster.hierarchy
import scipy.cluster.info
import scipy.cluster.setup
import scipy.cluster.setupscons
import scipy.cluster.vq
import scipy.constants
import scipy.constants.codata
import scipy.constants.constants
import scipy.constants.setup
import scipy.fftpack
import scipy.fftpack._fftpack
import scipy.fftpack.basic
import scipy.fftpack.convolve
import scipy.fftpack.fftpack_version
import scipy.fftpack.helper
import scipy.fftpack.info
import scipy.fftpack.pseudo_diffs
import scipy.fftpack.realtransforms
import scipy.fftpack.setup
import scipy.fftpack.setupscons
import scipy.integrate
import scipy.integrate._dop
import scipy.integrate._odepack
import scipy.integrate._quadpack
import scipy.integrate.info
import scipy.integrate.ode
import scipy.integrate.odepack
import scipy.integrate.quadpack
import scipy.integrate.quadrature
import scipy.integrate.setup
import scipy.integrate.setupscons
import scipy.integrate.vode
import scipy.interpolate
import scipy.interpolate._fitpack
import scipy.interpolate._interpolate
import scipy.interpolate.dfitpack
import scipy.interpolate.fitpack
import scipy.interpolate.fitpack2
import scipy.interpolate.generate_interpnd
import scipy.interpolate.info
import scipy.interpolate.interpnd
import scipy.interpolate.interpnd_info
import scipy.interpolate.interpolate
import scipy.interpolate.interpolate_wrapper
import scipy.interpolate.ndgriddata
import scipy.interpolate.polyint
import scipy.interpolate.rbf
import scipy.interpolate.setup
import scipy.interpolate.setupscons
import scipy.io
import scipy.io.arff
import scipy.io.arff.arffread
import scipy.io.arff.myfunctools
import scipy.io.arff.setup
import scipy.io.arff.utils
import scipy.io.data_store
import scipy.io.dumb_shelve
import scipy.io.dumbdbm_patched
import scipy.io.idl
import scipy.io.info
import scipy.io.matlab
import scipy.io.matlab.byteordercodes
import scipy.io.matlab.mio
import scipy.io.matlab.mio4
import scipy.io.matlab.mio5
import scipy.io.matlab.mio5_params
import scipy.io.matlab.mio5_utils
import scipy.io.matlab.mio_utils
import scipy.io.matlab.miobase
import scipy.io.matlab.setup
import scipy.io.matlab.setupscons
import scipy.io.matlab.streams
import scipy.io.mmio
import scipy.io.netcdf
import scipy.io.setup
import scipy.io.setupscons
import scipy.io.wavfile
import scipy.lib
import scipy.lib.blas
import scipy.lib.blas.cblas
import scipy.lib.blas.fblas
import scipy.lib.blas.info
import scipy.lib.blas.scons_support
import scipy.lib.blas.setup
import scipy.lib.blas.setupscons
import scipy.lib.info
import scipy.lib.lapack
import scipy.lib.lapack.atlas_version
import scipy.lib.lapack.calc_lwork
import scipy.lib.lapack.clapack
import scipy.lib.lapack.flapack
import scipy.lib.lapack.info
import scipy.lib.lapack.scons_support
import scipy.lib.lapack.setup
import scipy.lib.lapack.setupscons
import scipy.lib.setup
import scipy.lib.setupscons
import scipy.linalg
import scipy.linalg._flinalg
import scipy.linalg.atlas_version
import scipy.linalg.basic
import scipy.linalg.blas
import scipy.linalg.calc_lwork
import scipy.linalg.cblas
import scipy.linalg.clapack
import scipy.linalg.decomp
import scipy.linalg.decomp_cholesky
import scipy.linalg.decomp_lu
import scipy.linalg.decomp_qr
import scipy.linalg.decomp_schur
import scipy.linalg.decomp_svd
import scipy.linalg.fblas
import scipy.linalg.flapack
import scipy.linalg.flinalg
import scipy.linalg.info
import scipy.linalg.interface_gen
import scipy.linalg.lapack
import scipy.linalg.linalg_version
import scipy.linalg.matfuncs
import scipy.linalg.misc
import scipy.linalg.scons_support
import scipy.linalg.setup
import scipy.linalg.setup_atlas_version
import scipy.linalg.setupscons
import scipy.linalg.special_matrices
import scipy.maxentropy
import scipy.maxentropy.info
import scipy.maxentropy.maxentropy
import scipy.maxentropy.maxentutils
import scipy.maxentropy.setup
import scipy.maxentropy.setupscons
import scipy.misc
import scipy.misc.common
import scipy.misc.doccer
import scipy.misc.info
import scipy.misc.pilutil
import scipy.misc.setup
import scipy.misc.setupscons
import scipy.ndimage
import scipy.ndimage._nd_image
import scipy.ndimage._ni_support
import scipy.ndimage.filters
import scipy.ndimage.fourier
import scipy.ndimage.info
import scipy.ndimage.interpolation
import scipy.ndimage.io
import scipy.ndimage.measurements
import scipy.ndimage.morphology
import scipy.ndimage.setup
import scipy.ndimage.setupscons
import scipy.odr
import scipy.odr.__odrpack
import scipy.odr.info
import scipy.odr.models
import scipy.odr.odrpack
import scipy.odr.setup
import scipy.odr.setupscons
import scipy.optimize
import scipy.optimize._cobyla
import scipy.optimize._lbfgsb
import scipy.optimize._minpack
import scipy.optimize._nnls
import scipy.optimize._slsqp
import scipy.optimize._tstutils
import scipy.optimize._zeros
import scipy.optimize.anneal
import scipy.optimize.cobyla
import scipy.optimize.info
import scipy.optimize.lbfgsb
import scipy.optimize.linesearch
import scipy.optimize.minpack
import scipy.optimize.minpack2
import scipy.optimize.moduleTNC
import scipy.optimize.nnls
import scipy.optimize.nonlin
import scipy.optimize.optimize
import scipy.optimize.setup
import scipy.optimize.setupscons
import scipy.optimize.slsqp
import scipy.optimize.tnc
import scipy.optimize.zeros
import scipy.setup
import scipy.setupscons
import scipy.signal
import scipy.signal.bsplines
import scipy.signal.filter_design
import scipy.signal.fir_filter_design
import scipy.signal.info
import scipy.signal.ltisys
import scipy.signal.setup
import scipy.signal.setupscons
import scipy.signal.signaltools
import scipy.signal.sigtools
import scipy.signal.spline
import scipy.signal.waveforms
import scipy.signal.wavelets
import scipy.signal.windows
import scipy.sparse
import scipy.sparse.base
import scipy.sparse.bsr
import scipy.sparse.compressed
import scipy.sparse.construct
import scipy.sparse.coo
import scipy.sparse.csc
import scipy.sparse.csgraph
import scipy.sparse.csr
import scipy.sparse.data
import scipy.sparse.dia
import scipy.sparse.dok
import scipy.sparse.extract
import scipy.sparse.info
import scipy.sparse.lil
import scipy.sparse.linalg
import scipy.sparse.linalg.dsolve
import scipy.sparse.linalg.dsolve._superlu
import scipy.sparse.linalg.dsolve.info
import scipy.sparse.linalg.dsolve.linsolve
import scipy.sparse.linalg.dsolve.setup
import scipy.sparse.linalg.dsolve.setupscons
import scipy.sparse.linalg.dsolve.umfpack
import scipy.sparse.linalg.dsolve.umfpack.__umfpack
import scipy.sparse.linalg.dsolve.umfpack._umfpack
import scipy.sparse.linalg.dsolve.umfpack.info
import scipy.sparse.linalg.dsolve.umfpack.setup
import scipy.sparse.linalg.dsolve.umfpack.setupscons
import scipy.sparse.linalg.dsolve.umfpack.umfpack
import scipy.sparse.linalg.eigen
import scipy.sparse.linalg.eigen.arpack
import scipy.sparse.linalg.eigen.arpack._arpack
import scipy.sparse.linalg.eigen.arpack.arpack
import scipy.sparse.linalg.eigen.arpack.info
import scipy.sparse.linalg.eigen.arpack.setup
import scipy.sparse.linalg.eigen.arpack.setupscons
import scipy.sparse.linalg.eigen.info
import scipy.sparse.linalg.eigen.lobpcg
import scipy.sparse.linalg.eigen.lobpcg.info
import scipy.sparse.linalg.eigen.lobpcg.lobpcg
import scipy.sparse.linalg.eigen.lobpcg.setup
import scipy.sparse.linalg.eigen.lobpcg.setupscons
import scipy.sparse.linalg.eigen.setup
import scipy.sparse.linalg.eigen.setupscons
import scipy.sparse.linalg.info
import scipy.sparse.linalg.interface
import scipy.sparse.linalg.isolve
import scipy.sparse.linalg.isolve._iterative
import scipy.sparse.linalg.isolve.iterative
import scipy.sparse.linalg.isolve.lgmres
import scipy.sparse.linalg.isolve.lsqr
import scipy.sparse.linalg.isolve.minres
import scipy.sparse.linalg.isolve.setup
import scipy.sparse.linalg.isolve.setupscons
import scipy.sparse.linalg.isolve.utils
import scipy.sparse.linalg.setup
import scipy.sparse.linalg.setupscons
import scipy.sparse.setup
import scipy.sparse.setupscons
import scipy.sparse.sparsetools
import scipy.sparse.sparsetools._bsr
import scipy.sparse.sparsetools._coo
import scipy.sparse.sparsetools._csc
import scipy.sparse.sparsetools._csgraph
import scipy.sparse.sparsetools._csr
import scipy.sparse.sparsetools._dia
import scipy.sparse.sparsetools.bsr
import scipy.sparse.sparsetools.coo
import scipy.sparse.sparsetools.csc
import scipy.sparse.sparsetools.csgraph
import scipy.sparse.sparsetools.csr
import scipy.sparse.sparsetools.dia
import scipy.sparse.sparsetools.setup
import scipy.sparse.sparsetools.setupscons
import scipy.sparse.spfuncs
import scipy.sparse.sputils
import scipy.spatial
import scipy.spatial._distance_wrap
import scipy.spatial.ckdtree
import scipy.spatial.distance
import scipy.spatial.generate_qhull
import scipy.spatial.info
import scipy.spatial.kdtree
import scipy.spatial.qhull
import scipy.spatial.setup
import scipy.spatial.setupscons
import scipy.special
import scipy.special._cephes
import scipy.special.basic
import scipy.special.gendoc
import scipy.special.info
import scipy.special.lambertw
import scipy.special.orthogonal
import scipy.special.orthogonal_eval
import scipy.special.setup
import scipy.special.setupscons
import scipy.special.specfun
import scipy.special.special_version
import scipy.special.spfun_stats
import scipy.stats
import scipy.stats._support
import scipy.stats.distributions
import scipy.stats.futil
import scipy.stats.info
import scipy.stats.kde
import scipy.stats.morestats
import scipy.stats.mstats
import scipy.stats.mstats_basic
import scipy.stats.mstats_extras
import scipy.stats.mvn
import scipy.stats.rv
import scipy.stats.setup
import scipy.stats.setupscons
import scipy.stats.statlib
import scipy.stats.stats
import scipy.stats.vonmises
import scipy.stats.vonmises_cython
import scipy.version
import scipy.weave
import scipy.weave.accelerate_tools
import scipy.weave.ast_tools
import scipy.weave.base_info
import scipy.weave.base_spec
import scipy.weave.blitz_spec
import scipy.weave.blitz_tools
import scipy.weave.build_tools
import scipy.weave.bytecodecompiler
import scipy.weave.c_spec
import scipy.weave.catalog
import scipy.weave.common_info
import scipy.weave.converters
import scipy.weave.cpp_namespace_spec
import scipy.weave.ext_tools
import scipy.weave.info
import scipy.weave.inline_tools
import scipy.weave.md5_load
import scipy.weave.numpy_scalar_spec
import scipy.weave.platform_info
import scipy.weave.setup
import scipy.weave.setupscons
import scipy.weave.size_check
import scipy.weave.slice_handler
import scipy.weave.standard_array_spec
import scipy.weave.swig2_spec
import scipy.weave.swigptr
import scipy.weave.swigptr2
import scipy.weave.vtk_spec
import scipy.weave.weave_version
